### PR TITLE
Imem now

### PR DESCRIPTION
**Pull request by acautin**
Modified imem to use a 4 tuple as a replacement of imem_now in preparation to its deprecation.

### CODE REVIEW

**Comment by acautin** [comment]
@stoch I think you have forgotten to keep the 3-tuple implementation on imem_datatype, I got errors trying to open a ddLog after migrating to this branch.

```
imem_datatype:timestamp_to_io({1492,668149,935747}). ** exception error: no function clause matching 
                    imem_datatype:timestamp_to_io({1492,668149,935747},
                                                  6,eu) (src/imem_datatype.erl, line 1192)
```

And the higher error on dderl for reference, it seems it can't encode rowfun result:

```
{'EXIT',<0.1530.0>,{{case_clause,[[123,["1492",44,"668149",44,"935747"],125]]},[{gen_adapter,'-r2jsn/3-lc$^0/1-0-',1,[{file,"src/gen_adapter.erl"},{line,668}]},{gen_adapter,'-r2jsn/3-lc$^0/1-0-',1,[{file,"src/gen_adapter.erl"},{line,683}]},{gen_adapter,r2jsn,3,[{file,"src/gen_adapter.erl"},{line,668}]},{gen_adapter,gui_resp,2,[{file,"src/gen_adapter.erl"},{line,628}]},{gen_adapter,'-build_resp_fun/3-fun-2-',4,[{file,"src/gen_adapter.erl"},{line,689}]},{dderl_fsm,gui_response,2,[{file,"src/dderl_fsm.erl"},{line,1744}]},{dderl_fsm,filling,2,[{file,"src/dderl_fsm.erl"},{line,767}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,518}]}]}}
```

**Comment by stoch** [comment]
@acautin Added 2 commits for timestamp support. Please continue tests with these.

**Comment by acautin** [comment]
thanks @stoch it is working fine now when opening old and new log tables 👍
btw, I wish you a very happy birthday, and many more to come 🎂

**Comment by shamis** [comment]
@stoch [imem_meta:now/0](https://github.com/K2InformaticsGmbH/imem/pull/151/files#diff-b9d56b9cd9d41945452e3b6b83a4b3eaR157) is used here but i think its not being exported in imem_meta. 
Wish you a very Happy birthday

**Comment by stoch** [comment]
@shamis Added one more commit for timestamp handling (abandoning now() and replacing with time(), time_uid() and integer_uid().

**Pull request merged**
