### PR TITLE
Support of SELECT DISTINCT and GROUP BY

### PR DESCRIPTION
**Pull request by walter-weinmann**
Support of SELECT DISTINCT and GROUP BY regarding distinct result columns in the SELECT clause.

### CODE REVIEW

**Comment by c-bik** [comment]
@stoch Assigning for review/comment/merge!

**Comment by acautin** [comment]
@walter-weinmann I am not seeing the cleanup of the ets tables when the statement dies, it is possible that this generates some orphan ets in case some of the statements die ?.

**Comment by walter-weinmann** [comment]
The implementation logic in imem is as follows:

# imem_sql_select:exec

### determine if the aggregation feature is required:

```erlang
{_, ColMapGroupBy} = lists:keyfind('group by', 1, SelectSections),
IsDistinct = case length(ColMapGroupBy) of
                 0 ->
                     case lists:keyfind(opt, 1, SelectSections) of
                         false -> false;
                         {_, OptDistinct} ->
                             case OptDistinct == <<"distinct">> of
                                 true -> true;
                                 _ -> false
                             end
                     end;
                 _ -> true
             end,
```
### aggregation uses via imem_datatype:select_rowfun_raw & imem_datatype:select_rowfun_str an ets table to mark the duplicates

```erlang
RowFun = case IsDistinct of
             true ->
                 case ets:info(?MODULE) of
                     undefined ->
                         ets:new(?MODULE, [named_table, public, set]);
                     _ -> ok
                 end,
                 Key = erlang:phash2(Stmt),
                 true = ets:insert(?MODULE, {Key, []}),
                 case ?DefaultRendering of
                     raw ->
                         imem_datatype:select_rowfun_raw(ColMap1, {?MODULE, Key});
                     str ->
                         imem_datatype:select_rowfun_str(ColMap1, {?MODULE, Key}, ?GET_DATE_FORMAT(IsSec), ?GET_NUM_FORMAT(IsSec), ?GET_STR_FORMAT(IsSec))
                 end;
             false ->
                 case ?DefaultRendering of
                     raw -> imem_datatype:select_rowfun_raw(ColMap1);
                     str ->
                         imem_datatype:select_rowfun_str(ColMap1, ?GET_DATE_FORMAT(IsSec), ?GET_NUM_FORMAT(IsSec), ?GET_STR_FORMAT(IsSec))
                 end
         end,
```

# imem_datatype:select_rowfun_raw & select_rowfun_str:

### duplicates are returned as empty lists:

```erlang
select_rowfun_raw(ColMap, {TableId, Key}) ->
    fun(Recs) ->
        [{_, Distincts}] = ets:lookup(TableId, Key),
        RT = select_rowfun_raw(Recs, ColMap, []),
        case lists:member(RT, Distincts) of
            false ->
                true = ets:insert(TableId, {Key, [RT | Distincts]}),
                RT;
            _ ->
                []
        end
    end.

select_rowfun_str(ColMap, {TableId, Key}, DateFmt, NumFmt, StrFmt) ->
    fun(Recs) ->
        [{_, Distincts}] = ets:lookup(TableId, Key),
        RT = select_rowfun_str(Recs, ColMap, DateFmt, NumFmt, StrFmt, []),
        case lists:member(RT, Distincts) of
            false ->
                true = ets:insert(TableId, {Key, [RT | Distincts]}),
                RT;
            _ ->
                []
        end
    end.
```

# imem_statement/result_tuples & receive_tuples & result_tuples_sort:

### only non-empty lists are filtered:

```erlang
result_tuples(List, RowFun) when is_list(List), is_function(RowFun) ->
    lists:filter(fun(X) ->
        tuple_size(X) > 0 end, [list_to_tuple(R) || R <- lists:map(RowFun, List)]).

receive_tuples(#stmtResult{stmtRef=StmtRef,rowFun=RowFun}=StmtResult,Complete,Timeout,Acc) ->   
...
            case lists:usort([element(1, SR) || SR <- Unchecked]) of
                [StmtRef] -> 
                    % ?LogDebug("Unchecked receive result :~n~p~n",[Unchecked]),               
                    List = lists:flatten([element(1,element(2, T)) || T <- Unchecked]),
                    RT = lists:filter(fun(X) ->
                        tuple_size(X) > 0 end, result_tuples(List, RowFun)),
                    if 
                        length(RT) =< 10 ->
                            % ?LogDebug("Received:~n~p~n", [RT])

result_tuples_sort(List,RowFun,SortFun) when is_list(List), is_function(RowFun), is_function(SortFun) -> 
    lists:filter(fun(X) ->
        tuple_size(X) > 0 end, [list_to_tuple(R) || R <- lists:map(RowFun, recs_sort(List, SortFun))]).
```

### My assumption was that it is not necessary to clean up the ets table since it is related to the process, the module and the hash of the statement.

**Comment by acautin** [comment]
The necessity to clean up or not will depend if the process owner of the ets table is cleared after a table is closed or is related to the session, I haven't reviewed it in detail yet, but maybe you can help me out with some steps if you have time:

- executing the select with the aggregation
- note the table id (and maybe the process creating it)
- close the dderl resulting table
- check whether the ets table with aggregated data still exists.

I will check if myself later if you don't have time, and thanks for your contributions. 👍

**Pull request closed without merging**
