### PR TITLE
Deleted client search bug fix

### PR DESCRIPTION
**Pull request by shamis**
Deleted client search was returning clients that were not deleted. Fixed that.

Fixes https://github.com/K2InformaticsGmbH/sbsgui/issues/692

### CODE REVIEW

**Comment by c-bik** [comment]
"Deleted client search was returning clients that were not deleted. Fixed that."
-- isn't a relevant comment for IMEM.

Please change to a IMEM specific comment describing what is fixed in imem!

**Comment by acautin** [comment]
@c-bik can you elaborate as to why the comment is not appropriated, as it is exactly what was fixed. Cheers!

**Comment by c-bik** [comment]
@acautin isn't it obvious? There isn't any "Client" in `imem_dal_skvh`!

**Comment by acautin** [comment]
@c-bik the modified function is called ``find_deleted_clients`` maybe the name should be more generic then too ?

**Comment by c-bik** [comment]
@acautin absolutely!

**Pull request merged**
